### PR TITLE
remove graphicsmagic dep

### PR DESCRIPTION
**Pull request by christopher5106**
Works on Mac os and Ubuntu Docker kaixhin/cuda-torch:latest

I was not able to install graphicsmagic on kaixhin/cuda-torch:latest.

So I think it is a better solution to use the package image than graphicsmagick

### CODE REVIEW

**Comment by benglard** [comment]
Comments:
1. I think the code could actually be a bit simpler (not need ffi): [example](https://groups.google.com/d/msg/torch7/OcuxmWmQXgo/mEdUPATJDwAJ)
2. Please make sure totensor still works besides just making images

**Comment by christopher5106** [comment]
I removed ffi as you proposed. 
I'm not sure to understand because it seems you use totensor only for images (with graphicsmagicks as well).

**Comment by benglard** [comment]
merged, thanks!

**Comment by christopher5106** [comment]
Great

**Pull request merged**
